Exceptions that are thrown in AsyncCheckpointRunnable#run and subsequently being handled in AsyncCheckpointRunnable#handleExecutionException are never logged on the TaskExecutor side, and are only forwarded to the JobMaster.