
    final RandomAccessFile raf;
    try {
      raf = new RandomAccessFile(file, "r");
    }
    catch (FileNotFoundException e) {
      sendError(ctx, NOT_FOUND);
      return;
    }


If there is exception after raf is created but before method returns, raf would be left unclosed.