During testing of new setup of directory server I tried to setup the server with custom keystore
and I didn't provide a password for keystore.

./setup -h pyforge.example.com --adminConnectorPort 4447 -D cn=myself -w password --useJavaKeystore /tmp/custom_keystore



The setup failed with error:

Validating parameters .....Done.
Configuring Certificates .....Done.
Configuring server .....Done.
Starting Directory Server ............Error......
Error Starting Directory Server.
See /tmp/opendj-setup-4818798470476713875.log for a detailed log of the failed
operation.
Please report this error and provide the log file mentioned above.



The mentioned file contains following error message:

category=CORE severity=NOTICE msgID=139 msg=The Directory Server has sent an alert 
notification generated by class org.opends.server.core.DirectoryServer (alert type 
org.opends.server.DirectoryServerShutdown, alert ID org.opends.messages.core-141): The 
Directory Server has started the shutdown process. The shutdown was initiated by an 
instance of class org.opends.server.core.DirectoryServer and the reason provided for the 
shutdown was An error occurred while trying to start the Directory Server: 
InitializationException: An error occurred while attempting to initialize the SSL context for use
 in the LDAP Connection Handler: An error occurred while trying to create a key manager 
factory to access the contents of keystore file /home/ondrej/DATA/repositories/pyforge-
framework/results/20170126-075632/setup_group/tmp/custom_keystore: 
UnrecoverableKeyException(Password must not be null) 
(id=org.opends.messages.extension-83) (LDAPConnectionHandler.java:429 
AdministrationConnector.java:113 ConnectionHandlerConfigManager.java:241 
ConnectionHandlerConfigManager.java:203 DirectoryServer.java:1744 
DirectoryServer.java:1474 DirectoryServer.java:5026)




I expected the failure during parsing command line parameters rather than failure during the startup phase.