Problem

When using dsreplication configure, DJ raises some errors in access log.

Problem is present on 5.5.0 and 6.0.0 but not on 3.5.2
Abandon returns ldap status code 119

Failed ABANDON operation in access log with 119 ldap rc. 
 I ran a test during 3 days (CTS reaper test) and this error occurs 188 times during all the test duration time.


./ldap-access.audit.json:{"eventName":"DJ-LDAP","client":{"ip":"127.0.0.1","port":51483},"server":{"ip":"127.0.0.1","port":5444},"request":{"protocol":"LDAPS","operation":"ABANDON","connId":2,"msgId":10,"idToAbandon":9},"transactionId":"0","response":{"status":"FAILED","statusCode":"119","elapsedTime":0,"elapsedTimeUnits":"MILLISECONDS"},"timestamp":"2018-01-12T10:02:36.821Z","_id":"06ef3009-6565-47e7-ac27-5def98714274-151"}


Search returns ldap status code 32

	Search on "cn=replication server,cn=Multimaster Synchronization,cn=Synchronization Providers,cn=config"





./ldap-access.audit.json:{"eventName":"DJ-LDAP","client":{"ip":"127.0.0.1","port":51479},"server":{"ip":"127.0.0.1","port":5444},"request":{"protocol":"LDAPS","operation":"SEARCH","connId":1,"msgId":71,"dn":"cn=replication server,cn=Multimaster Synchronization,cn=Synchronization Providers,cn=config","scope":"base","filter":"(objectClass=*)","attrs":["1.1"]},"transactionId":"0","response":{"status":"FAILED","statusCode":"32","elapsedTime":1,"elapsedTimeUnits":"MILLISECONDS","detail":"No Such Entry: The entry 'cn=replication server,cn=Multimaster Synchronization,cn=Synchronization Providers,cn=config' does not exist","nentries":0},"timestamp":"2018-01-12T10:02:36.930Z","_id":"06ef3009-6565-47e7-ac27-5def98714274-181"}


	Search on "cn=Servers,cn=admin data"





./ldap-access.audit.json:{"eventName":"DJ-LDAP","client":{"ip":"127.0.0.1","port":51479},"server":{"ip":"127.0.0.1","port":5444},"request":{"protocol":"LDAPS","operation":"SEARCH","connId":1,"msgId":51,"dn":"cn=Servers,cn=admin data","scope":"base","filter":"(objectClass=*)","attrs":["1.1"]},"transactionId":"0","response":{"status":"FAILED","statusCode":"32","elapsedTime":1,"elapsedTimeUnits":"MILLISECONDS","detail":"Entry cn=Servers,cn=admin data specified as the search base DN does not exist","nentries":0},"timestamp":"2018-01-12T10:02:36.482Z","_id":"06ef3009-6565-47e7-ac27-5def98714274-111"}

How to reproduce

Run pyforge test with 2 replicated DJ instances and check ldap-access.audit.json file

For example :


./run-pybot.py -c perf -s bbc.reaper_poc -n OpenAM 


 

 

 