Found with rev 3f5be2f0ba8

We set up 2 DSs and 2 RSs, replicated, and a proxy configured with RS1 as a primary replication server and a group id corresponding to DJ1-RS1.

We kill DJ1. It triggers an error in RS1 log files:

in ./proxy_group/ReplicationDiscovery/RS1/opendj/logs/replication:

[13/Aug/2018:17:37:12 +0200] category=SYNC severity=NOTICE msgID=313 msg=An I/O error occurred while reading replication messages from Replica DS(3) for domain "cn=schema". The connection will close and replication server (1296) will not process any more updates from it. Reported error is: IOException: no more data (SessionImpl.java:308 SessionImpl.java:276 ServerReader.java:82)
[13/Aug/2018:17:37:12 +0200] category=SYNC severity=NOTICE msgID=313 msg=An I/O error occurred while reading replication messages from Replica DS(3) for domain "cn=admin data". The connection will close and replication server (1296) will not process any more updates from it. Reported error is: IOException: no more data (SessionImpl.java:308 SessionImpl.java:276 ServerReader.java:82)
[13/Aug/2018:17:37:12 +0200] category=SYNC severity=NOTICE msgID=313 msg=An I/O error occurred while reading replication messages from Replica DS(3) for domain "dc=com". The connection will close and replication server (1296) will not process any more updates from it. Reported error is: IOException: no more data (SessionImpl.java:308 SessionImpl.java:276 ServerReader.java:82) 


To reproduce:


./run-pybot.py -s proxy_group.ReplicationDiscovery -t failover_stop_group_modify_op opendj

