Found with 6.5.0 rev (d370c5695e1)

When using rest2ldap with DJ, trying to patch a non existing resource, we had the following issue:

*** Patch non-existing resource ***
	
====================
Sending HTTP Request
==================== 	
Url: http://ig-linux.internal.forgerock.com:8080/api/patch/users/user.1000
None
method: patch
params: {'_prettyPrint': 'true'}
headers: {'Content-Type': 'application/json'}
certificate: None
auth: ('admin_user', 'admin_password')
data: [{"operation": "add", "field": "street", "value": "addStreet"}] 	

http -v --follow --all -a admin_user:admin_password PATCH "http://ig-linux.internal.forgerock.com:8080/api/patch/users/user.1000" Content-Type:"application/json" 	
Starting new HTTP connection (1): ig-linux.internal.forgerock.com 	
http://ig-linux.internal.forgerock.com:8080 "PATCH /api/patch/users/user.1000?_prettyPrint=true HTTP/1.1" 500 111 	
=======================
Receiving HTTP Response
======================= 	
status code: 500
content: 
{
  "code" : 500,
  "reason" : "Internal Server Error",
  "message" : "java.util.concurrent.TimeoutException"
}


unfortunately, we have lost the log files for this problem.
We will update this issue with more details once we manage to reproduce it.

happened with:


./run-pybot.py -v -n -s rest2ldap_group.PatchEmbedded -t Non_Existing_Resource opendj

