Loading a column that does not exist generates the following error:

2009-09-01 21:29:15,161 [main] ERROR org.apache.pig.tools.grunt.Grunt - ERROR 2999: Unexpected internal error. null

Example is like this:

STORE urls2 into '$output' using org.apache.pig.table.pig.TableStorer('md5:string, url:string');

and then in another pig script, I load the table:

input = LOAD '$output' USING org.apache.pig.table.pig.TableLoader('md5,url, domain');

where domain is a column that does not exist.